In [1]:
import pandas as pd
import numpy as np

In [2]:
datasets = pd.read_csv('../datasets/20-02-23/LSP3-10.csv')

In [3]:
datasets

,Datum_probe,Max_force,Set_Dim_A,Set_Dim_B,Set_Dim_C,Pivot_Height,Projection1
0,486.760010,1283,0.5165,0.4975,0.4920,-9.388,0.4797
1,485.410004,798,0.5116,0.4909,0.4967,-9.375,0.5121
2,358.459992,1180,0.5686,0.5209,0.5568,-9.416,0.6075
3,300.779999,501,0.5379,0.5239,0.5240,-9.386,0.5208
4,302.369995,561,0.5689,0.5737,0.5565,-9.383,0.5426
...,...,...,...,...,...,...,...
553727,488.529999,561,0.4991,0.4859,0.5103,-9.379,0.5282
553728,459.410004,1685,0.5157,0.5035,0.5308,-9.384,0.5553
553729,485.660004,1303,0.4943,0.4793,0.5045,-9.372,0.5251
553730,464.540008,1016,0.5041,0.4997,0.5317,-9.382,0.5614
553731,461.000000,1342,0.5113,0.5099,0.5418,-9.388,0.5659

In [4]:
max=(datasets['Projection1'])

In [5]:
datasets['Projection1']=pd.cut(datasets['Projection1'],bins=[-np.inf,0.4647,0.5664,np.inf],labels=['fail_low','pass','fail_high'])
datasets['Projection1'].replace('fail_low','fail',inplace=True)
datasets['Projection1'].replace('fail_high','fail',inplace=True)

In [6]:
datasets

,Datum_probe,Max_force,Set_Dim_A,Set_Dim_B,Set_Dim_C,Pivot_Height,Projection1
0,486.760010,1283,0.5165,0.4975,0.4920,-9.388,pass
1,485.410004,798,0.5116,0.4909,0.4967,-9.375,pass
2,358.459992,1180,0.5686,0.5209,0.5568,-9.416,fail
3,300.779999,501,0.5379,0.5239,0.5240,-9.386,pass
4,302.369995,561,0.5689,0.5737,0.5565,-9.383,pass
...,...,...,...,...,...,...,...
553727,488.529999,561,0.4991,0.4859,0.5103,-9.379,pass
553728,459.410004,1685,0.5157,0.5035,0.5308,-9.384,pass
553729,485.660004,1303,0.4943,0.4793,0.5045,-9.372,pass
553730,464.540008,1016,0.5041,0.4997,0.5317,-9.382,pass
553731,461.000000,1342,0.5113,0.5099,0.5418,-9.388,pass

In [7]:
from collections import Counter
print(Counter(datasets['Projection1']))

Counter({'pass': 550061, 'fail': 3671})

In [8]:
from imblearn.over_sampling import SMOTE
# over_sampling คือการทำค่า fail 1284 ให้เท่ากับค่า pass 271k เพื่อให้ data ในการ train เพิ่มมากขึ้น
from collections import Counter

k = 3
X = datasets.loc[:, datasets.columns != 'Projection1']
y = datasets.Projection1

# sampling_strategy=0.1 oversampling 10%
sm = SMOTE(sampling_strategy='minority', k_neighbors=k, random_state=100)
X_res, y_res = sm.fit_resample(X, y)

datasets = pd.concat([pd.DataFrame(X_res), pd.DataFrame(y_res)], axis=1)

In [9]:
from collections import Counter
print(Counter(datasets['Projection1']))

Counter({'pass': 550061, 'fail': 550061})

In [10]:
from collections import Counter
print(Counter(datasets['Projection1']))

Counter({'pass': 550061, 'fail': 550061})

In [11]:
datasets

,Datum_probe,Max_force,Set_Dim_A,Set_Dim_B,Set_Dim_C,Pivot_Height,Projection1
0,486.760010,1283,0.516500,0.497500,0.492000,-9.388000,pass
1,485.410004,798,0.511600,0.490900,0.496700,-9.375000,pass
2,358.459992,1180,0.568600,0.520900,0.556800,-9.416000,fail
3,300.779999,501,0.537900,0.523900,0.524000,-9.386000,pass
4,302.369995,561,0.568900,0.573700,0.556500,-9.383000,pass
...,...,...,...,...,...,...,...
1100117,304.380005,826,0.432692,0.448396,0.443065,-9.382000,fail
1100118,459.997922,1259,0.509879,0.506538,0.526872,-9.379551,fail
1100119,460.588562,1216,0.507993,0.505243,0.533282,-9.383761,fail
1100120,303.709992,1193,0.446484,0.442451,0.451285,-9.385000,fail
1100121,468.076617,1440,0.515117,0.489865,0.532373,-9.376260,fail

In [12]:
Datum_3LCL = 125.0000
Datum_2LCL = 250.0000
Datum_LCL = 375.0000
Datum_CL = 500.0000
Datum_UCL =625.0000
Datum_2UCL = 750.0000
Datum_3UCL = 875.000

Max_3LCL = 300.00
Max_2LCL = 833.33
Max_LCL = 1366.67
Max_CL = 1900.00
Max_UCL = 2433.33
Max_2UCL = 2966.67
Max_3UCL = 3500.00

Set_Dim_A_3LCL = 0.4775
Set_Dim_A_2LCL = 0.4902
Set_Dim_A_LCL = 0.5029
Set_Dim_A_CL = 0.5156
Set_Dim_A_UCL = 0.5283
Set_Dim_A_2UCL = 0.541
Set_Dim_A_3UCL = 0.5537


Set_Dim_B_3LCL = 0.4775
Set_Dim_B_2LCL = 0.4902
Set_Dim_B_LCL = 0.5029
Set_Dim_B_CL = 0.5156
Set_Dim_B_UCL = 0.5283
Set_Dim_B_2UCL =0.541
Set_Dim_B_3UCL = 0.5537

Set_Dim_C_3LCL = 0.4775
Set_Dim_C_2LCL = 0.4902
Set_Dim_C_LCL = 0.5029
Set_Dim_C_CL = 0.5156
Set_Dim_C_UCL = 0.5283
Set_Dim_C_2UCL =0.541
Set_Dim_C_3UCL = 0.5537

Pivot_Height_3LCL = -9.4031
Pivot_Height_2LCL = -9.3946
Pivot_Height_LCL = -9.3861
Pivot_Height_CL = -9.3777
Pivot_Height_UCL = -9.3692
Pivot_Height_2UCL = -9.3607
Pivot_Height_3UCL = -9.3523


datasets['Datum_probe']=pd.cut(datasets['Datum_probe'],bins=[-np.inf, Datum_3LCL, Datum_2LCL, Datum_LCL, Datum_CL, Datum_UCL, Datum_2UCL, Datum_3UCL, np.inf],labels=['A','B','C','D','E','F','G','H'])

datasets['Max_force']=pd.cut(datasets['Max_force'],bins=[-np.inf, Max_3LCL, Max_2LCL, Max_LCL, Max_CL, Max_UCL, Max_2UCL, Max_3UCL, np.inf],labels=['A','B','C','D','E','F','G','H'])

datasets['Set_Dim_A']=pd.cut(datasets['Set_Dim_A'],bins=[-np.inf, Set_Dim_A_3LCL, Set_Dim_A_2LCL, Set_Dim_A_LCL, Set_Dim_A_CL, Set_Dim_A_UCL, Set_Dim_A_2UCL, Set_Dim_A_3UCL,np.inf],labels=['A','B','C','D','E','F','G','H'])

datasets['Set_Dim_B']=pd.cut(datasets['Set_Dim_B'],bins=[-np.inf, Set_Dim_B_3LCL, Set_Dim_B_2LCL, Set_Dim_B_LCL, Set_Dim_B_CL, Set_Dim_B_UCL, Set_Dim_B_2UCL, Set_Dim_B_3UCL, np.inf],labels=['A','B','C','D','E','F','G','H'])

datasets['Set_Dim_C']=pd.cut(datasets['Set_Dim_C'],bins=[-np.inf, Set_Dim_C_3LCL, Set_Dim_C_2LCL, Set_Dim_C_LCL, Set_Dim_C_CL, Set_Dim_C_UCL, Set_Dim_C_2UCL, Set_Dim_C_3UCL, np.inf],labels=['A','B','C','D','E','F','G','H'])

datasets['Pivot_Height']=pd.cut(datasets['Pivot_Height'],bins=[-np.inf, Pivot_Height_3LCL, Pivot_Height_2LCL, Pivot_Height_LCL, Pivot_Height_CL, Pivot_Height_UCL, Pivot_Height_2UCL, Pivot_Height_3UCL,np.inf],labels=['A','B','C','D','E','F','G','H'])

In [13]:
Datum_3LCL

125.0

In [14]:
# Datum_3LCL = ('{:.4f}'.format(Datum_3LCL))
# Datum_2LCL = ('{:.4f}'.format(Datum_2LCL))
# Datum_LCL = ('{:.4f}'.format(Datum_LCL ))
# Datum_CL = ('{:.4f}'.format(Datum_CL ))
# Datum_UCL = ('{:.4f}'.format(Datum_UCL ))
# Datum_2UCL = ('{:.4f}'.format(Datum_2UCL ))
# Datum_3UCL =('{:.4f}'.format(Datum_3UCL ))
# Max_3LCL = ('{:.4f}'.format(Max_3LCL ))
# Max_2LCL = ('{:.4f}'.format(Max_2LCL ) )
# Max_LCL = ('{:.4f}'.format(Max_LCL )  )
# Max_CL = ('{:.4f}'.format(Max_CL ))
# Max_UCL = ('{:.4f}'.format(Max_UCL ))
# Max_2UCL = ('{:.4f}'.format(Max_2UCL ))
# Max_3UCL = ('{:.4f}'.format(Max_3UCL ))
# Set_Dim_A_3LCL = ('{:.4f}'.format(Set_Dim_A_3LCL))
# Set_Dim_A_2LCL = ('{:.4f}'.format(Set_Dim_A_2LCL))
# Set_Dim_A_LCL = ('{:.4f}'.format(Set_Dim_A_LCL))
# Set_Dim_A_CL = ('{:.4f}'.format(Set_Dim_A_CL ))
# Set_Dim_A_UCL = ('{:.4f}'.format(Set_Dim_A_UCL ))
# Set_Dim_A_2UCL = ('{:.4f}'.format(Set_Dim_A_2UCL ))
# Set_Dim_A_3UCL = ('{:.4f}'.format(Set_Dim_A_3UCL ))
# Set_Dim_B_3LCL = ('{:.4f}'.format(Set_Dim_B_3LCL))
# Set_Dim_B_2LCL = ('{:.4f}'.format(Set_Dim_B_2LCL))
# Set_Dim_B_LCL = ('{:.4f}'.format(Set_Dim_B_LCL))
# Set_Dim_B_CL = ('{:.4f}'.format(Set_Dim_B_CL ))
# Set_Dim_B_UCL = ('{:.4f}'.format(Set_Dim_B_UCL ))
# Set_Dim_B_2UCL = ('{:.4f}'.format(Set_Dim_B_2UCL ))
# Set_Dim_B_3UCL = ('{:.4f}'.format(Set_Dim_B_3UCL ))
# Set_Dim_C_3LCL = ('{:.4f}'.format(Set_Dim_C_3LCL))
# Set_Dim_C_2LCL = ('{:.4f}'.format(Set_Dim_C_2LCL))
# Set_Dim_C_LCL = ('{:.4f}'.format(Set_Dim_C_LCL))
# Set_Dim_C_CL = ('{:.4f}'.format(Set_Dim_C_CL ))
# Set_Dim_C_UCL = ('{:.4f}'.format(Set_Dim_C_UCL ))
# Set_Dim_C_2UCL = ('{:.4f}'.format(Set_Dim_C_2UCL ))
# Set_Dim_C_3UCL = ('{:.4f}'.format(Set_Dim_C_3UCL ))

# Pivot_Height_3LCL = ('{:.4f}'.format(Pivot_Height_3LCL))
# Pivot_Height_2LCL = ('{:.4f}'.format(Pivot_Height_2LCL))
# Pivot_Height_LCL = ('{:.4f}'.format(Pivot_Height_LCL))
# Pivot_Height_CL = ('{:.4f}'.format(Pivot_Height_CL ))
# Pivot_Height_UCL = ('{:.4f}'.format(Pivot_Height_UCL ))
# Pivot_Height_2UCL = ('{:.4f}'.format(Pivot_Height_2UCL ))
# Pivot_Height_3UCL = ('{:.4f}'.format(Pivot_Height_3UCL ))

In [15]:
# from pandas import DataFrame
# data ={'Length':['A','B','C','D','E','F','G','H'],
# 'Datum_probe':[('<='),(Datum_3LCL),(Datum_2LCL),(Datum_LCL ),(Datum_CL ),(Datum_UCL ),(Datum_2UCL ),('>=' )],
# 'Datum_probe1':[(Datum_3LCL),(Datum_2LCL),(Datum_LCL ),(Datum_CL ),(Datum_UCL ),(Datum_2UCL ),(Datum_3UCL ),(Datum_3UCL )],

# 'Max_force':[('<='),(Max_3LCL),(Max_2LCL),(Max_LCL ),(Max_CL ),(Max_UCL ),(Max_2UCL ),(Max_3UCL )],
# 'Max_force1':[(Max_3LCL),(Max_2LCL),(Max_LCL ),(Max_CL ),(Max_UCL ),(Max_2UCL ),(Max_3UCL ),('>=' )],

# 'Set_Dim_A':[('<='),(Set_Dim_A_3LCL),(Set_Dim_A_2LCL),(Set_Dim_A_LCL),(Set_Dim_A_CL ),(Set_Dim_A_UCL ),(Set_Dim_A_2UCL ),(Set_Dim_A_3UCL)],
# 'Set_Dim_A1':[(Set_Dim_A_3LCL),(Set_Dim_A_2LCL),(Set_Dim_A_LCL),(Set_Dim_A_CL ),(Set_Dim_A_UCL ),(Set_Dim_A_2UCL ),(Set_Dim_A_3UCL),('>=' )],

# 'Set_Dim_B':[('<='),(Set_Dim_B_3LCL),(Set_Dim_B_2LCL),(Set_Dim_B_LCL),(Set_Dim_B_CL ),(Set_Dim_B_UCL ),(Set_Dim_B_2UCL ),(Set_Dim_B_3UCL)],
# 'Set_Dim_B1':[(Set_Dim_B_3LCL),(Set_Dim_B_2LCL),(Set_Dim_B_LCL),(Set_Dim_B_CL ),(Set_Dim_B_UCL ),(Set_Dim_B_2UCL ),(Set_Dim_B_3UCL),('>=' )],

# 'Set_Dim_C':[('<='),(Set_Dim_C_3LCL),(Set_Dim_C_2LCL),(Set_Dim_C_LCL),(Set_Dim_C_CL ),(Set_Dim_C_UCL ),(Set_Dim_C_2UCL ),(Set_Dim_C_3UCL)],
# 'Set_Dim_C1':[(Set_Dim_C_3LCL),(Set_Dim_C_2LCL),(Set_Dim_C_LCL),(Set_Dim_C_CL ),(Set_Dim_C_UCL ),(Set_Dim_C_2UCL ),(Set_Dim_C_3UCL),('>=' )],

# 'Set_Dim_C':[('<='),(Set_Dim_C_3LCL),(Set_Dim_C_2LCL),(Set_Dim_C_LCL),(Set_Dim_C_CL ),(Set_Dim_C_UCL ),(Set_Dim_C_2UCL ),(Set_Dim_C_3UCL)],
# 'Set_Dim_C1':[(Set_Dim_C_3LCL),(Set_Dim_C_2LCL),(Set_Dim_C_LCL),(Set_Dim_C_CL ),(Set_Dim_C_UCL ),(Set_Dim_C_2UCL ),(Set_Dim_C_3UCL),('>=' )],

# 'Pivot_Height':[('<='),(Pivot_Height_3LCL),(Pivot_Height_2LCL),(Pivot_Height_LCL),(Pivot_Height_CL ),(Pivot_Height_UCL ),(Pivot_Height_2UCL ),(Pivot_Height_3UCL)],
# 'Pivot_Height_1':[(Pivot_Height_3LCL),(Pivot_Height_2LCL),(Pivot_Height_LCL),(Pivot_Height_CL ),(Pivot_Height_UCL ),(Pivot_Height_2UCL ),(Pivot_Height_3UCL),('>=' )],

# }
# df = pd.DataFrame(data,columns=['Length','Datum_probe','Datum_probe1','Max_force','Max_force1','Set_Dim_A','Set_Dim_A1','Set_Dim_B','Set_Dim_B1','Set_Dim_C','Set_Dim_C1','Pivot_Height','Pivot_Height_1'])
# print("displaying the dataframe with data as record")
# print(df)
# print("-------------------------------Converting into csv file with a new a new file name ------------------------------------")
# df.to_csv("C:\\Users\\IT\\Desktop\\Date ML\\NewLSP3-10-10Feb.csv")
# df=pd.read_csv("C:\\Users\\IT\\Desktop\\Date ML\\NewLSP3-10-10Feb.csv")
# print(df)

In [16]:
datasets

,Datum_probe,Max_force,Set_Dim_A,Set_Dim_B,Set_Dim_C,Pivot_Height,Projection1
0,D,C,E,C,C,C,pass
1,D,B,D,C,C,E,pass
2,C,C,H,E,H,A,fail
3,C,B,F,E,E,D,pass
4,C,B,H,H,H,D,pass
...,...,...,...,...,...,...,...
1100117,C,B,A,A,A,D,fail
1100118,D,C,D,D,E,D,fail
1100119,D,C,D,D,F,D,fail
1100120,C,C,A,A,A,D,fail
1100121,D,D,D,B,F,E,fail

In [17]:
from pyarc import CBA, TransactionDB
from sklearn.model_selection import train_test_split 
from sklearn.metrics import classification_report

train, test = train_test_split(datasets, test_size=0.1)

txns_train = TransactionDB.from_DataFrame(train)
txns_test = TransactionDB.from_DataFrame(test)

cba = CBA (support = 0.09, confidence = 0.8, algorithm ='m1')
cba.fit(txns_train)

y_pred = cba.predict(txns_test)
y_test = test['Projection1']
print ((classification_report(y_test,y_pred)))

In [ ]:
datasp =((classification_report(y_test,y_pred)))

In [ ]:
datasp.split("\n")

['              precision    recall  f1-score   support',
 '',
 '        fail       0.91      0.26      0.41     55060',
 '        pass       0.57      0.97      0.72     54953',
 '',
 '    accuracy                           0.62    110013',
 '   macro avg       0.74      0.62      0.56    110013',
 'weighted avg       0.74      0.62      0.56    110013',
 '']

In [ ]:
line=['3-10'       ,datasp[14:23],datasp[27:33],datasp[35:43],datasp[46:53]]
print(line)
fail=[datasp[63:67] ,datasp[74:78],datasp[84:88],datasp[94:98],datasp[103:108]]
print(fail)
pass1=[datasp[117:121],datasp[128:132],datasp[138:142],datasp[148:152],datasp[157:162]]
print(pass1)
accuracy=[datasp[168:176],[]             ,[]             ,datasp[203:207],datasp[211:217]]
print(accuracy)
macro_avg=[datasp[221:230],datasp[237:241],datasp[247:251],datasp[257:261],datasp[265:271]]
print(macro_avg)
weighted_avg=[datasp[272:284],datasp[291:295],datasp[301:305],datasp[311:315],datasp[319:325]]
print(weighted_avg)

['3-14', 'precision', 'recall', 'f1-score', 'support']
['fail', '0.91', '0.26', '0.41', '55060']
['pass', '0.57', '0.97', '0.72', '54953']
['accuracy', [], [], '0.62', '110013']
['macro avg', '0.74', '0.62', '0.56', '110013']
['weighted avg', '0.74', '0.62', '0.56', '110013']

In [ ]:
from pandas import DataFrame

data ={
'Details':[(datasp[63:67]),(datasp[117:121]),(datasp[168:176]),(datasp[221:230]),(datasp[272:284])
],
'precision':[datasp[74:78],datasp[128:132],(''),datasp[128:132],datasp[237:241]
],
'recall':[datasp[84:88],datasp[138:142],(''),datasp[247:251],datasp[301:305]
],
'f1-score':[datasp[94:98],datasp[148:152],(datasp[203:207]),datasp[257:261],datasp[311:315]
],

'support':[datasp[103:108],datasp[157:162],datasp[211:217],datasp[265:271],datasp[319:325]
],
}
df = pd.DataFrame(data,columns=['Details','precision','recall','f1-score','support'])
print("displaying the dataframe with data as record")
print(df)
print("-------------------------------Converting into csv file with a new a new file name ------------------------------------")
df.to_csv("C:\\Users\\IT\\Desktop\\Date ML\\LSP3-10.csv")
df=pd.read_csv("C:\\Users\\IT\\Desktop\\Date ML\\LSP3-10.csv")
print(df)

displaying the dataframe with data as record
        Details precision recall f1-score support
0          fail      0.91   0.26     0.41   55060
1          pass      0.57   0.97     0.72   54953
2      accuracy                      0.62  110013
3     macro avg      0.57   0.62     0.56  110013
4  weighted avg      0.74   0.62     0.56  110013
-------------------------------Converting into csv file with a new a new file name ------------------------------------
   Unnamed: 0       Details  precision  recall  f1-score  support
0           0          fail       0.91    0.26      0.41    55060
1           1          pass       0.57    0.97      0.72    54953
2           2      accuracy        NaN     NaN      0.62   110013
3           3     macro avg       0.57    0.62      0.56   110013
4           4  weighted avg       0.74    0.62      0.56   110013

In [ ]:
cba.clf.rules

[CAR {Max_force=C,Set_Dim_C=F} => {Projection1=fail} sup: 0.10 conf: 0.93 len: 3, id: 20,
 CAR {Datum_probe=D,Set_Dim_C=F,Pivot_Height=D} => {Projection1=fail} sup: 0.10 conf: 0.91 len: 4, id: 21]

In [ ]:
cba1=cba.clf.rules

In [ ]:
len(cba1)

2

In [ ]:
from pandas import DataFrame
data ={
'DataCBA':[(cba1[0])
,(cba1[1])
# ,(cba1[2])
# ,(cba1[3])
# ,(cba1[4]),(cba1[5]),(cba1[6]),(cba1[7]),(cba1[8]),(cba1[9]),(cba1[10]),(cba1[11])
],

}
df = pd.DataFrame(data,columns=['DataCBA'])
print("displaying the dataframe with data as record")
print(df)
print("-------------------------------Converting into csv file with a new a new file name ------------------------------------")
df.to_csv("C:\\Users\\IT\\Desktop\\Date ML\\NewLSP3-10 6KPIV.csv")
df=pd.read_csv("C:\\Users\\IT\\Desktop\\Date ML\\NewLSP3-10 6KPIV.csv")
print(df)

displaying the dataframe with data as record
                                             DataCBA
0  CAR {Max_force=C,Set_Dim_C=F} => {Projection1=...
1  CAR {Datum_probe=D,Set_Dim_C=F,Pivot_Height=D}...
-------------------------------Converting into csv file with a new a new file name ------------------------------------
   Unnamed: 0                                            DataCBA
0           0  CAR {Max_force=C,Set_Dim_C=F} => {Projection1=...
1           1  CAR {Datum_probe=D,Set_Dim_C=F,Pivot_Height=D}...

In [ ]:
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report

# train, test = train_test_split(datasets, test_size=0.01)
# print(train.shape,test.shape)

# print(Counter(test['Projection1']))

# txns_train = TransactionDB.from_DataFrame(train)
# txns_test = TransactionDB.from_DataFrame(test)

In [ ]:
# from pyarc.algorithms import (
#     top_rules,
#     createCARs,
#     generateCARs,
#     M1Algorithm,
#     M2Algorithm,
# )

# rules = top_rules(txns_train.string_representation, minlen=2, init_maxlen=4, max_iterations=50)

# # convert them to class association rules
# cars = createCARs(rules)

# # classifier = M1Algorithm(cars, txns_train).build()
# classifier = M2Algorithm(cars, txns_train).build()

# accuracy = classifier.test_transactions(txns_test)

# y_pred = classifier.predict_all(txns_test)
# y_test = test['Projection1']
# print(classification_report(y_pred, y_test))